package tsi.lv.mindbag

/**
 * Created by Vladislav on 12/31/2017.
 */

val RESULT_CODE_SEARCH_BACK_CLICK = 123
val RESULT_CODE_SEARCH_BOOK_SELECTED = 120

val EXTRA_DIALOG_DELETE_NOTE_ID = "EXTRA_DIALOG_DELETE_NOTE_ID"
val EXTRA_DIALOG_DELETE_BOOK_ID = "EXTRA_DIALOG_DELETE_BOOK_ID"
val EXTRA_DIALOG_DELETE_BOOK_TITLE = "EXTRA_DIALOG_DELETE_BOOK_TITLE"

val EXTRA_ACTIVITY_DISPLAYED_NOTE_ID = "EXTRA_ACTIVITY_DISPLAYED_NOTE_ID"